[project]
name = "email-chat-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai-agents>=0.0.11",
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
]
